[server]
host = "0.0.0.0"
port = 3030

[general]
ignore_robots_txt = false
default_lang = "en-US"
max_redirect_hops = 5 # set 0 to disallow redirects
response_timeout = 20000 # milliseconds
operation_timeout = 60000 # milliseconds
content_length_limit = "10 MB" # set 0 to disable, you can use units like "10 MB", "500 KB", "1 GB" (https://docs.rs/parse-size/latest/parse_size/)

[security]
secret_key = ""
block_non_global_ips = true

[plugins]
disabled = []

[cache] # redis cache
enabled = false
host = "127.0.0.1"
port = 6379
# prefix = "prod"
# db = 0
# username = ""
# password = ""

# [sentry]
# dsn = ""