[build]
pre-build = ["apt-get update && apt-get install --assume-yes --no-install-recommends libclang-10-dev clang-10"]

[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:main"

[target.armv7-unknown-linux-gnueabihf.env]
passthrough = ["LIBCLANG_PATH=/usr/lib/llvm-10/lib", """BINDGEN_EXTRA_CLANG_ARGS_armv7-unknown-linux-gnueabihf=--sysroot=/usr/arm-linux-gnueabihf -idirafter/usr/include"""]